Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/RescueStandardError:
  Enabled: false
